Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false

  config.vm.provision :shell, :path => "install.sh"

  config.hostmanager.enabled = true
  config.hostmanager.manage_guest = true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
  end
  config.vm.define "worker2" do |c|
      c.vm.hostname = "worker2"
      c.vm.network "private_network", ip: "192.168.77.22"
      c.vm.network "forwarded_port", guest: 10250, host: 11250
      c.vm.network "forwarded_port", guest: 10255, host: 11255
  end
    config.vm.define "worker3" do |c|
      c.vm.hostname = "worker3"
      c.vm.network "private_network", ip: "192.168.77.23"
      c.vm.network "forwarded_port", guest: 10250, host: 11250
      c.vm.network "forwarded_port", guest: 10255, host: 11255
  end
  config.vm.define "worker4" do |c|
      c.vm.hostname = "worker4"
      c.vm.network "private_network", ip: "192.168.77.24"
      c.vm.network "forwarded_port", guest: 10250, host: 11250
      c.vm.network "forwarded_port", guest: 10255, host: 11255
  end
end
